FROM apache/airflow:2.7.0-python3.9

USER root

COPY requirements.txt /requirements.txt

USER airflow

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /requirements.txt && \
    pip install psycopg2-binary \
    celery[redis] \
    apache-airflow-providers-postgres \
    apache-airflow-providers-celery

ENV AIRFLOW_HOME=/opt/airflow

EXPOSE 8080

CMD ["airflow", "webserver"]
